# kind cluster configuration for CKA Simulator
# 1 control-plane + 2 worker nodes
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cka-simulator
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node-role=control-plane"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node-role=worker,disk=ssd"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node-role=worker,disk=hdd"
